# Generated by Django 5.1.1 on 2024-10-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='types',
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('144', '144'), ('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080')], default='simple', max_length=18),
        ),
    ]
